### ISSUE TITLE
debug sample

### ISSUE THREAD

**Issue by ludoch** [elefeint/examples#6]
The NPE is at https://github.com/GoogleCloudPlatform/appengine-java-standard/blob/ed04358f94bcb08c2d2b9da9f80025024f6fdc6e/api_dev/src/main/java/com/google/appengine/tools/development/SharedMain.java#L197

it seems to say that timezone is for some reason null...
Maybe by setting in command line the user property https://github.com/GoogleCloudPlatform/appengine-java-standard/blob/ed04358f94bcb08c2d2b9da9f80025024f6fdc6e/api_dev/src/main/java/com/google/appengine/tools/development/SharedMain.java#L158

would help?

**Comment by ludoch** [comment]
For some reasons,
        String originalTimeZone = System.getProperty("user.timezone");


is empty ("") on Jdk11, but null in jdk17... Will do a CL.

**Comment by elefeint** [comment]
Setting user property does work! -- `--jvm_flag="-Duser.timezone='GMT-5'"`.

Full command line:
```
 $GCP_CLI/bin/java_dev_appserver.sh --jvm_flag="--add-opens" --jvm_flag="java.base/java.net=ALL-UNNAMED" --jvm_flag="--add-opens" --jvm_flag="java.base/sun.net.www.protocol.http=ALL-UNNAMED" --jvm_flag="--add-opens" --jvm_flag="java.base/sun.net.www.protocol.https=ALL-UNNAMED" --jvm_flag="-Duser.timezone='GMT-5'" ./target/springboot-helloworld-j17-0.0.1-SNAPSHOT
```

**Comment by elefeint** [comment]
This unblocks me, thank you!
